import {request} from '../lib/api.js';
import {SERVICES,minutes,clock,logo,icon} from '../lib/ui.js';
let state;const root=document.querySelector('#app');
function render(){document.documentElement.dataset.theme=state.settings.theme;const total=state.totalUsageSeconds;
 root.innerHTML=`<header><button class="brand" id="brand-open"><img src="../assets/poses/companion.png" alt=""><span><strong>MindMoth</strong><small>A little less feed.</small></span></button><button class="icon-button" id="open" aria-label="Open dashboard">${icon('arrow')}</button></header><section class="companion-card"><span class="eyebrow">YOUR ATTENTION, TODAY</span><div class="companion-row"><img id="companion" src="../assets/mascots/${state.stage.id}.png" alt="${state.stage.label} MindMoth"><div class="score"><strong id="health">${state.health}</strong><span>Focus health</span><small id="stage">${state.stage.label}</small></div></div><div class="usage-line"><span id="usage">${minutes(total)} of ${state.settings.dailyGoalMinutes}m today</span><span>Local only</span></div><progress id="usage-progress" max="${state.settings.dailyGoalMinutes*60}" value="${Math.min(total,state.settings.dailyGoalMinutes*60)}" aria-label="Daily usage"></progress></section><section class="services"><div class="section-head"><h2>Protected services</h2><button id="manage">Manage</button></div><div class="site-grid">${SERVICES.map(([host,label,key])=>`<button type="button" class="site-chip" data-service="${host}" title="Manage ${label} protection">${logo(key,label)}<span><strong>${label}</strong><small data-status="${host}">${state.settings.protectedSites[host].enabled?'Protected':'Off / paused'} · <em data-usage="${host}">${minutes(state.usageToday[host])}</em></small></span></button>`).join('')}</div></section><button class="focus-button" id="focus">${icon(state.focus.active?'lock':'play')}<span>${state.focus.active?'View focus session':'Start 25m focus'}</span></button><button class="dashboard-button" id="dashboard">Open MindMoth dashboard ${icon('arrow')}</button><footer><a href="https://x.com/Carbonthecoder" target="_blank" rel="noopener noreferrer">Made by Carbonthecoder</a></footer>`;
}
root.addEventListener('click',async event=>{const b=event.target.closest('button');if(!b)return;try{
 if(['open','dashboard','brand-open'].includes(b.id))return await request('OPEN_DASHBOARD',{page:'home'});
 if(b.id==='manage'||b.dataset.service)return await request('OPEN_DASHBOARD',{page:'blockers'});
 if(b.id==='focus'){b.disabled=true;if(state.focus.active)await request('OPEN_DASHBOARD',{page:'focus'});else{state=(await request('FOCUS_ACTION',{action:'start',minutes:25})).state;render();}b.disabled=false;}
 }catch(e){document.querySelector('#error').textContent=e.message;b.disabled=false;}});
try{state=(await request('GET_APP_STATE')).state;render();}catch(e){document.querySelector('#error').textContent=e.message;root.innerHTML='<p class="loading">Reload MindMoth from your browser’s extensions page, then reopen it. Your data is not deleted.</p>';}
setInterval(()=>{if(!state?.focus.active)return;const b=document.querySelector('#focus span');if(b)b.textContent=`Focus: ${clock((state.focus.endsAt-Date.now())/1000)} · Open`;},1000);
