import {request} from '../lib/api.js';
import {REPO,SERVICES,esc,minutes,clock,logo,icon,stats} from '../lib/ui.js';
import {openReview,resumeReview} from './review-ui.js';
const pages=['home','history','focus','blockers','settings','challenges','welcome'];
let state=(await request('GET_APP_STATE')).state;
let page=parsePage(),focusPreset=25,navigationId=0;
const root=document.querySelector('#app');
function parsePage(){const p=location.hash.slice(1);return pages?.includes(p)?p:'home';}
function credit(){return `<footer class="credit"><a href="https://x.com/Carbonthecoder" target="_blank" rel="noopener noreferrer">Made by Carbonthecoder</a><span>v${chrome.runtime.getManifest().version}</span></footer>`;}
function brand(){return `<button type="button" class="brand" data-page="home"><img src="../assets/poses/companion.png" alt=""><span><strong>MindMoth</strong><small>A calmer internet for a brighter you</small></span></button>`;}
function nav(active){return `<nav aria-label="Main navigation">${[['home','Home','home'],['history','Stats','chart'],['settings','Settings','settings']].map(([key,label,i])=>`<button type="button" class="nav-button ${key===active?'selected':''}" data-page="${key}" ${key===active?'aria-current="page"':''}>${icon(i)}${label}</button>`).join('')}</nav>`;}
function status(){const count=Object.values(state.settings.protectedSites).filter(x=>x.enabled).length;return `<span class="status ${count?'on':''}"><i></i>${state.focus.active?'Focus active':count===4?'Protection on':count?`${count} services protected`:'Protection off'}</span>`;}
function header(active=page){return `<header class="top-header">${brand()}<div class="header-actions">${status()}${nav(active)}</div></header>`;}
function frame(body,cls=''){return `<div class="page-shell"><div class="app-frame ${cls}">${header()}${body}${credit()}</div></div>`;}
function serviceCard(host,label,key){const cfg=state.settings.protectedSites[host];return `<article class="service-card">${logo(key,label)}<div class="service-copy"><strong>${label}</strong><small>${state.focus.active?'Focus locked':cfg.paused?'Paused':cfg.enabled?'Protected':'Off'}</small></div><span class="usage" data-usage="${host}" title="Active usage today">${minutes(state.usageToday[host])}</span><button type="button" class="icon-button service-more" data-service="${host}" aria-label="Manage ${label} protection">${icon('settings')}</button></article>`;}
function home(){const on=Object.values(state.settings.protectedSites).some(s=>s.enabled);return frame(`
<section class="home-banner"><div class="banner-copy"><span class="eyebrow">${state.focus.active?'FOCUS IS ACTIVE':on?'YOU’RE PROTECTED':'YOUR ATTENTION, YOUR CHOICE'}</span><h1>${on||state.focus.active?'Distractions meet<br>their match.':'Give your attention<br>a little space.'}</h1><p>One clear intention before the feed.<br>More room for what you actually came to do.</p><button type="button" class="button light-button" data-page="blockers">${icon('shield')}Manage protection</button></div><span class="hand-note">Small steps,<br>brighter days ♡</span></section>
<section class="panel preset-panel"><div class="section-head"><div><h2>Focus presets</h2><p>Pick a pause. Make room for something else.</p></div><button type="button" class="text-button" data-page="focus">See all ${icon('arrow')}</button></div><div class="preset-grid">${[['grass','Touch Grass','Step away from the feed.',15],['deep','Deep Focus','One task. Fewer detours.',25],['study','Study Sprint','A little time to learn.',50]].map(([key,title,sub,time])=>`<button type="button" class="preset ${key}" data-preset="${time}" data-page="focus" aria-label="Prepare ${time} minute ${title} session"><span class="preset-copy"><strong>${title}</strong><small>${sub}</small><span class="round-arrow">${icon('arrow')}</span></span><img src="../assets/poses/${key}.png" alt="" loading="lazy"><span class="duration">${time}m</span></button>`).join('')}</div></section>
<section class="panel"><div class="section-head"><div><h2>Protected services</h2><p>Whole-site protection, including direct posts and videos.</p></div><button type="button" class="button small" data-page="blockers">${icon('shield')}Manage</button></div><div class="service-grid">${SERVICES.map(s=>serviceCard(...s)).join('')}</div></section>
<section class="closing-banner"><div><strong>A calmer, kinder internet is possible.</strong><p>A little friction between an impulse and an endless feed.</p></div><span class="hand-note">Focus<br>fuels freedom ♡</span></section>`,'home-frame');}
function challengeCards(all=false){const a=stats(state).achievements;return `<div class="challenge-grid">${a.map(x=>`<article class="challenge ${x.tone}"><div class="challenge-icons">${icon(x.icon)}${icon(x.current>=x.total?'check':'gift')}</div><h3>${x.title}</h3><p>${x.detail}</p><div class="challenge-bottom"><progress value="${Math.min(x.current,x.total)}" max="${x.total}" aria-label="${x.title}"></progress><span>${Math.min(x.current,x.total)}/${x.total}</span></div>${all?`<small>${x.current>=x.total?'Milestone reached':'In progress'}. Based on recorded activity only.</small>`:''}</article>`).join('')}</div>`;}
function history(){const s=stats(state);return `<div class="page-shell stats-shell"><div class="stats-frame"><aside class="sidebar">${brand()}<nav aria-label="Stats navigation">${[['home','Home','home'],['focus','Focus','clock'],['history','Streaks','flame'],['challenges','Milestones','gift'],['blockers','Blockers','shield'],['settings','Settings','settings']].map(([p,l,i])=>`<button type="button" class="side-link ${p===page?'selected':''}" data-page="${p}">${icon(i)}${l}</button>`).join('')}</nav><div class="sidebar-note">${icon('leaf')}<p>A little less feed.<br>A little more day.</p></div></aside><main class="stats-main"><header class="stats-head"><div><h1>${s.streak?'You’re on a roll!':'Start a quieter streak.'}</h1><p>Small choices, recorded honestly.</p></div><span class="small-note">${icon('sun')} One day at a time.</span></header>
<section class="streak-banner"><img src="../assets/poses/streak.png" alt="MindMoth with a leaf scarf"><div class="streak-copy"><strong>${s.streak}</strong><h2>${s.streak===1?'Day streak':'Day streak'}</h2><p>Completed, recorded days<br>within your daily goal.</p></div><span class="hand-note">Small choices<br>make a brighter<br>tomorrow. ♡</span></section>
<section class="panel week-panel"><div><h2>This week</h2><div class="week-row">${s.week.map(d=>`<div class="week-day ${d.status}" title="${d.date}: ${d.status==='today'?'In progress':d.status==='untracked'?'Not recorded':d.status}"><span>${d.status==='done'?icon('leaf'):d.status==='today'?icon('sun'):'·'}</span><small>${d.label}</small></div>`).join('')}</div></div><div class="week-aside">${icon('leaf')}<p>Progress<br>over perfection.</p><small>Today stays in progress<br>until the day ends.</small></div></section>
<section class="panel"><div class="section-head"><div><h2>Challenges & milestones</h2><p>Measured progress. No invented rewards.</p></div><button type="button" class="text-button" data-page="challenges">View all ${icon('arrow')}</button></div>${challengeCards()}</section>${credit()}</main></div></div>`;}
function challenges(){return frame(`<section class="page-heading"><span class="eyebrow">SMALL STEPS, REAL PROGRESS</span><h1>Challenges & milestones</h1><p>Each card explains exactly what is counted. No points for untracked activity.</p></section><section class="panel">${challengeCards(true)}<div class="info-note">${icon('book')}<p>A recorded day is a day MindMoth has data for. Missing days are not silently treated as perfect days. Focus sessions only count when their timer finishes.</p></div></section><button class="button back-button" data-page="history" type="button">Back to stats</button>`);}
function focus(){const active=state.focus.active;const remain=active?(state.focus.endsAt-Date.now())/1000:focusPreset*60;return `<div class="page-shell focus-shell"><div class="focus-frame"><header class="focus-header">${brand()}<div class="focus-nav"><button class="icon-button" data-page="home" aria-label="Home">${icon('home')}</button><button class="icon-button" data-page="settings" aria-label="Settings">${icon('settings')}</button></div></header><section class="garden-stage"><div class="timer-copy"><span class="eyebrow">FOCUS TO A BRIGHTER YOU</span><h1 id="focus-clock">${clock(remain)}</h1><p>${active?'Stay with one thing. The feed can wait.':'Deep work. Brighter days.'}</p></div><div class="garden-controls">${!active?`<div class="chips" aria-label="Focus duration">${[15,25,50,90].map(n=>`<button data-preset="${n}" type="button" aria-pressed="${n===focusPreset}" class="chip ${n===focusPreset?'selected':''}">${n}m</button>`).join('')}</div>`:''}<button type="button" class="focus-control ${active?'stop':''}" id="focus-toggle" aria-label="${active?'Review ending focus early':'Start focus session'}">${active?icon('lock')+'<span>End early</span>':icon('play')}</button><small>${active?'Ending early requires a review.':'A CALMER INTERNET AWAITS'}</small></div></section>${credit()}</div></div>`;}
function blockers(){return frame(`<section class="page-heading"><span class="eyebrow">PROTECTION, WITH INTENTION</span><h1>Keep the detours difficult.</h1><p>Turning protection back on is instant. Pausing or turning it off takes a deliberate review.</p></section><section class="panel"><div class="service-grid blocker-grid">${SERVICES.map(([host,label,key])=>{const cfg=state.settings.protectedSites[host];return `<article class="blocker-card">${logo(key,label)}<h2>${label}</h2><p>${host} and all its pages</p><span class="tag ${cfg.enabled?'on':''}">${cfg.paused?'Paused for up to 10 minutes':cfg.enabled?'Protected':'Off'}</span><button type="button" class="button ${cfg.enabled?'':'primary'}" data-service="${host}">${cfg.enabled?'Review a pause / turn off':'Enable protection'}</button></article>`;}).join('')}</div><div class="info-note">${icon('shield')}<p>Focus mode locks all four services for the session, even if a service was previously paused. These controls do not bypass an active focus session.</p></div></section>`);}
function settings(){return frame(`<section class="page-heading"><span class="eyebrow">MINDMOTH, YOUR WAY</span><h1>Settings</h1><p>Simple controls. Deliberate exceptions.</p></section><section class="settings-grid"><article class="setting-card"><h2>Daily goal</h2><p>Sets your usage goal, not an automatic unlock.</p><div class="chips">${[15,30,45,60,90,120].map(n=>`<button class="chip ${state.settings.dailyGoalMinutes===n?'selected':''}" data-goal="${n}" aria-pressed="${state.settings.dailyGoalMinutes===n}" type="button">${n}m</button>`).join('')}</div></article><article class="setting-card"><h2>Intervention strength</h2><p>Aggressive adds reading, waits, short visits and cooldowns.</p><div class="chips">${['firm','aggressive'].map(n=>`<button class="chip ${state.settings.interventionStrength===n?'selected':''}" data-strength="${n}" type="button" aria-pressed="${state.settings.interventionStrength===n}">${n==='firm'?'Firm':'Aggressive'}</button>`).join('')}</div><small>Reducing friction requires a review.</small></article><article class="setting-card"><h2>Appearance</h2><p>Dark by default. Light uses the cream and pastel artwork.</p><div class="chips">${['dark','light'].map(n=>`<button type="button" class="chip ${state.settings.theme===n?'selected':''}" data-theme="${n}" aria-pressed="${state.settings.theme===n}">${n==='dark'?'Dark':'Light'}</button>`).join('')}</div></article><article class="setting-card"><h2>Your local data</h2><p>No account. No telemetry. Export a backup before resetting.</p><div class="setting-actions"><button type="button" class="button" id="export">${icon('download')}Export data</button><button type="button" class="button danger" id="reset">Review reset</button></div></article></section><section class="panel privacy-note"><h2>Built in the open</h2><p>MindMoth is a voluntary browser blocker, not device management or a medical tool. “Focus health” is a playful usage score. The browser still lets you disable or uninstall extensions.</p><a class="text-button" href="${REPO}" target="_blank" rel="noopener noreferrer">View source on GitHub ${icon('arrow')}</a></section>`);}
function welcome(){return frame(`<section class="page-heading"><span class="eyebrow">WELCOME TO MINDMOTH</span><h1>A little friction.<br>A lot more intention.</h1><p>Pin MindMoth in your browser’s extension menu. X, Instagram, TikTok and YouTube are protected in this browser.</p><button type="button" class="button primary" data-page="home">Open MindMoth ${icon('arrow')}</button></section><section class="panel"><h2>Good to know</h2><p>Disabling a service inside MindMoth takes a cooling-off review. Focus mode blocks all four services. Dark mode is the default; Light is in Settings. Data stays in this browser profile.</p></section>`);}
function render(){document.documentElement.dataset.theme=state.settings.theme;root.innerHTML=({home,history,focus,blockers,settings,challenges,welcome}[page]||home)();}
export function toast(message,error=false){const el=document.querySelector('#feedback');el.textContent=message;el.className=error?'visible error':'visible';clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.className='',5000);}
async function navigate(next){if(!pages.includes(next))next='home';const id=++navigationId;state=(await request('GET_APP_STATE')).state;if(id!==navigationId)return;page=next;window.history.pushState({},'',`#${page}`);render();window.scrollTo({top:0,behavior:'instant'});}
function selected(group,value){root.querySelectorAll(`[data-${group}]`).forEach(b=>{const yes=b.dataset[group]===String(value);b.classList.toggle('selected',yes);b.setAttribute('aria-pressed',yes);});}
async function handleClick(event){const b=event.target.closest('button');if(!b||b.disabled)return;
 if(b.dataset.preset){focusPreset=Number(b.dataset.preset);if(b.dataset.page)return navigate('focus');selected('preset',focusPreset);document.querySelector('#focus-clock').textContent=clock(focusPreset*60);return;}
 if(b.dataset.page)return navigate(b.dataset.page);
 if(b.dataset.service){const host=b.dataset.service;if(state.settings.protectedSites[host].enabled){openReview(host,async next=>{state=next;render();toast('Protection updated.');});}else{state=(await request('ENABLE_SITE',{host})).state;render();toast('Protection enabled.');}return;}
 if(b.dataset.theme){state=(await request('UPDATE_SETTINGS',{patch:{theme:b.dataset.theme}})).state;document.documentElement.dataset.theme=state.settings.theme;selected('theme',state.settings.theme);return;}
 if(b.dataset.goal){state=(await request('UPDATE_SETTINGS',{patch:{dailyGoalMinutes:Number(b.dataset.goal)}})).state;selected('goal',state.settings.dailyGoalMinutes);toast('Daily goal saved.');return;}
 if(b.dataset.strength){if(b.dataset.strength===state.settings.interventionStrength)return;if(b.dataset.strength==='firm'){openReview('weaken',async next=>{state=next;render();});}else{state=(await request('UPDATE_SETTINGS',{patch:{interventionStrength:'aggressive'}})).state;selected('strength','aggressive');}return;}
 if(b.id==='focus-toggle'){if(state.focus.active)openReview('end-focus',async next=>{state=next;render();});else{b.disabled=true;try{state=(await request('FOCUS_ACTION',{action:'start',minutes:focusPreset})).state;render();}finally{b.disabled=false;}}return;}
 if(b.id==='reset'){openReview('reset',async next=>{state=next;await navigate('home');toast('Local data reset.');});return;}
 if(b.id==='export'){const {data}=await request('EXPORT_DATA');const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`mindmoth-backup-${state.date}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);toast('Backup downloaded.');}
}
root.addEventListener('click',event=>{handleClick(event).catch(error=>toast(error.message,true));});
window.addEventListener('popstate',()=>{page=parsePage();render();});
window.addEventListener('hashchange',()=>{page=parsePage();render();});
render();resumeReview(next=>{state=next;render();});
let checking=false;
setInterval(async()=>{
 if(state.focus.active){const value=Math.max(0,(state.focus.endsAt-Date.now())/1000);const el=document.querySelector('#focus-clock');if(el)el.textContent=clock(value);if(!value&&!checking){checking=true;try{state=(await request('GET_APP_STATE')).state;if(page==='focus')render();}catch(e){toast(e.message,true);}finally{checking=false;}}}
},1000);
